# Generated by Django 4.2.16 on 2024-11-27 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minasAirlines', '0002_hangar'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='hangar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='aeronaves', to='minasAirlines.hangar'),
        ),
    ]
